from __future__ import annotations

from pathlib import Path
import argparse
import hashlib
import json
import shutil
import zipfile


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for chunk in iter(lambda: f.read(8 * 1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


# Each record is: logical label, acceptable basename(s), exact raw SHA-256, destination.
# Hashes come from the canonical artifact manifests generated by the executed Phase7C-7D runs.
ARTIFACTS = [
    # ---------------- Phase7C: official split/data audit ----------------
    ('phase7c_patch_roles', ['phase7d_frozen_unique_patch_roles.csv.gz'],
     '7a396d0c61c6a78151a58b2c62dd016786ab1c4f9dd85f05eed5bde430ee4f05',
     'manifests/event_split/phase7d_frozen_unique_patch_roles.csv.gz'),
    ('phase7c_build_lock', ['phase7d_build_lock.json'],
     '1b3106fed81d4e98a0a0ca0ce55e77161aa5fa9b789316c6e5b567e8fa5a8ef4',
     'manifests/event_split/phase7d_build_lock.json'),
    ('phase7c_integrity_checks', ['phase7c_integrity_checks.csv'],
     'ef543cbb0e26c44def2843917262eaa4c9626ff4e419623a60a6d741ec3542a2',
     'results/development/phase7c_integrity_checks.csv'),
    ('phase7c_results_index', ['results_index.json'],
     'f3b3a4e56132247693ddd741d5289b2dec07b20378a6277ec245b7dc789182a6',
     'results/development/phase7c_results_index.json'),

    # ---------------- Phase7D-A: building manifests + frozen source ----------------
    ('phase7da_train_manifest', ['event_train_buildings.csv.gz'],
     'c82b2743f857a11ed7b390a06b4b2b24e6bebdbd7e925585221c66ba5a60e9d4',
     'manifests/buildings/event_train_buildings.csv.gz'),
    ('phase7da_val_manifest', ['event_val_buildings.csv.gz'],
     '44adcd20edcff627ef36ae9fbb7d259f0ca404ee86f343cea2313c6d3fefc35c',
     'manifests/buildings/event_val_buildings.csv.gz'),
    ('phase7da_test_manifest_sealed', ['event_test_buildings_SEALED.csv.gz'],
     '05546b6876cd3201eaa7a77ec31e96ce8ca18fb0ffa5e4cc3a9581a00ee0fcad',
     'manifests/buildings/event_test_buildings_SEALED.csv.gz'),
    ('phase7da_wrongpre_val_map', ['event_val_hard_wrongpre_donor_map.csv.gz'],
     '4bfb7d73e5cec58a70977ce719cb32f33e15b6e8f06edf917392f218801905a6',
     'manifests/wrong_pre/event_val_hard_wrongpre_donor_map.csv.gz'),
    ('phase7da_integrity_checks', ['phase7d_a_integrity_checks.csv'],
     '5d65f7e70dd26d41f82f56ff016e75a1e73949e29b1759e1453ebafffc71dec5',
     'results/development/phase7d_a_integrity_checks.csv'),
    ('phase7da_results_index', ['results_index.json'],
     '9bf205355896f363f02f29850c84d9db7ce51df6e92b8448ecc380de369cd574',
     'results/development/phase7d_a_results_index.json'),
    ('frozen_build_manifest_source', ['build_manifest.py'],
     '4337d8ec54d2fdaa5361e4c30e7544e16f0edf306f517dcff612b7fe12d7807a',
     'vendor/frozen_phase7d_source/src/data/build_manifest.py'),
    ('frozen_dataset_source', ['dataset.py'],
     '165a71c4ebf6adea14f20f735bc487e883c5448e5ccfaf4fe8b74e49a3a77044',
     'vendor/frozen_phase7d_source/src/data/dataset.py'),
    ('frozen_crop_source', ['crop_utils.py'],
     '8c34139a0f96eaf8246dd228cf27c83386d6c1ca049426c25d28666576589593',
     'vendor/frozen_phase7d_source/src/data/crop_utils.py'),
    ('frozen_model_source', ['damage_models.py'],
     '9f9ee3382902f339309ddf03a203b882d42e8674de7bf8ee3d18b14863478f2d',
     'vendor/frozen_phase7d_source/src/models/damage_models.py'),

    # ---------------- Phase7D-B: completed Seed42 experts ----------------
    ('phase7db_post_checkpoint', ['best_state_dict.pt'],
     'df6b607973ea74e1a6aa7eb640459b65c7a4e1bdaabc7fce956d2c757374967c',
     'checkpoints/experts/post_seed42_best_state_dict.pt'),
    ('phase7db_siamese_checkpoint', ['best_state_dict.pt'],
     '3d6466108cf44e994c0c7b7bb1745e549807d89601e45898911de34a455d73a5',
     'checkpoints/experts/siamese_seed42_best_state_dict.pt'),
    ('phase7db_val_post_predictions', ['event_val_post_only_predictions.csv.gz'],
     'e7c4081f0f754c5f867fcc94be2a6c62b96a409937fd098e3bd5222c43fdfe50',
     'predictions/development/event_val_post_only_predictions.csv.gz'),
    ('phase7db_val_siamese_predictions', ['event_val_siamese_predictions.csv.gz'],
     'a261bd855d81e71110459ca145060fea910b803f472675917f3c578d5c3b3fed',
     'predictions/development/event_val_siamese_predictions.csv.gz'),
    ('phase7db_val_wrongpre_predictions', ['event_val_siamese_wrongpre_predictions.csv.gz'],
     '64938aaba097aa18f21f31a5813cb82301ea5ef862194b5509ff8840a566d17d',
     'predictions/development/event_val_siamese_wrongpre_predictions.csv.gz'),
    ('phase7db_training_history', ['training_history.csv'],
     'c4f2e7cf5ec16fa36b6176f1b77cdef9fed1f5f8f285126a144d032670f6f51a',
     'results/development/phase7d_b_training_history.csv'),
    ('phase7db_environment', ['environment.json'],
     'eb5c1e87367ff9de2e80945ea877607806bb69ebc703beddcc64823a23052ec1',
     'results/development/phase7d_b_environment.json'),
    ('phase7db_results_index', ['results_index.json'],
     '4086d9a4c59c1f43027fbd6782553bc63e1939530b846fd4c91c0a26d7a0d301',
     'results/development/phase7d_b_results_index.json'),
    ('phase7db_wrongpre_metrics', ['wrongpre_metrics.json'],
     'd66d0e4b630703a54d73086d14953a56286afc0b945ac08e479c1baf284343fe',
     'results/development/phase7d_b_wrongpre_metrics.json'),

    # ---------------- Phase7D-C S1A: selection evidence ----------------
    ('phase7dc_s1a_protocol', ['phase7d_c_s1_protocol.json'],
     'f7308dc61dc32df3c16e77c441b98e72eadf14a110c520bb9070c5a07b7e54d6',
     'results/development/phase7d_c_selection_protocol.json'),
    ('phase7dc_s1a_selection_index', ['phase7d_c_s1_selection_index.json'],
     '3138d5251b0dc21c9f01559665f3bf62ce27dfa1e3b4f0b6bf959594e523717e',
     'results/development/phase7d_c_selection_index.json'),
    ('phase7dc_outer_split', ['outer_split_assignments.csv.gz'],
     '6f4c3050a91d2d772c4ea6d59ccf8e338b47deb661ecc98824fd540ce5feddf1',
     'manifests/router/outer_split_assignments.csv.gz'),
    ('phase7dc_inner_split', ['inner_neural_split_assignments.csv.gz'],
     '9887ce0cdff5d9c6fcab3b05089b9412af9d8c9722e7b826ea2edf23dbf31188',
     'manifests/router/inner_neural_split_assignments.csv.gz'),
    ('phase7dc_neural_epoch_history', ['neural_epoch_selection_history.csv'],
     'a819635542e25cbdc13f0dcdf795d3a9608d8f75b85ada352816cd818be63ad0',
     'results/development/neural_epoch_selection_history.csv'),
    ('phase7dc_static_alpha_selection', ['static_alpha_selection.csv'],
     '563858b3481efbc4139c0b7195b650d5b606bbff0d776b8995a93220a1897dcc',
     'results/development/static_alpha_selection.csv'),

    # ---------------- Phase7D-C S1B: final frozen routers + diagnostics ----------------
    ('phase7dc_final_neural', ['final_neural_safe_router.pt'],
     'ab94161da3331fd02cad8b4632375a3321159f5633f86fc212ec86b682d31a4b',
     'checkpoints/routers/final_neural_safe_router.pt'),
    ('phase7dc_final_logistic', ['final_logistic_soft_gate.joblib'],
     '8d0115705294bb2877341dc752854e7912c4cc83261ee9ed492731a862aa3372',
     'checkpoints/routers/final_logistic_soft_gate.joblib'),
    ('phase7dc_final_hgb', ['final_hgb_hard_router.joblib'],
     '72d84b25dea3053028c7905797c14d305da8c6f0b48cf1fd6742391a03d65028',
     'checkpoints/routers/final_hgb_hard_router.joblib'),
    ('phase7dc_final_alpha', ['final_static_alpha.json'],
     '2778cb68dd385953343cd1268e8b4f22060d21cb1e963325c0308114c7853b60',
     'checkpoints/routers/final_static_alpha.json'),
    ('phase7dc_diag_metrics', ['router_diag_metrics.csv'],
     '2f76a53f331d8f96b07711295f1607659cdc81aec7a7207e879607089874f9b2',
     'results/development/router_diag_metrics.csv'),
    ('phase7dc_diag_per_class', ['router_diag_per_class_f1.csv'],
     '40abc12060400fe83205ee02a56908ff549b5b6c5182fab2adbdfadec7c1436e',
     'results/development/router_diag_per_class_f1.csv'),
    ('phase7dc_diag_bootstrap', ['router_diag_scene_bootstrap.csv'],
     '2ec39b351448fb0083506e00b310a11eb0b3b6177b438b93b687a34c081c49b3',
     'results/development/router_diag_scene_bootstrap.csv'),
    ('phase7dc_utility_diagnostics', ['neural_utility_diagnostics.json'],
     '12792cb751e5fe5d912252405b78b2107c10155d60592e168ec87803531c6b6b',
     'results/development/neural_utility_diagnostics.json'),
    ('phase7dc_results_index', ['phase7d_c_s1_results_index.json'],
     'b14b6f44b8a4a759ab3be6a03ab19ea8685e4ee97e3e5545258d3c3c166adace',
     'results/development/phase7d_c_results_index.json'),

    # ---------------- Phase7D-D: final sealed six-event test ----------------
    ('phase7dd_test_buildings', ['event_test_buildings_rebuilt.csv.gz'],
     '1dda199c0faa444e955ecf7b131872dc5c5a713482914e821cd916aea4b37a2a',
     'manifests/buildings/event_test_buildings_rebuilt.csv.gz'),
    ('phase7dd_clean_expert_predictions', ['event_test_clean_expert_predictions.csv.gz'],
     'f0657fc72629acb8730464897c44040cde65942966a81f47c956f3c5b1bb09f2',
     'predictions/heldout_events/event_test_clean_expert_predictions.csv.gz'),
    ('phase7dd_wrongpre_predictions', ['event_test_wrongpre_siamese_predictions.csv.gz'],
     '5b85ea8ea298e3e840ea23b24731ba5b330a352fbb9993fd272a5a64bc027231',
     'predictions/heldout_events/event_test_wrongpre_siamese_predictions.csv.gz'),
    ('phase7dd_wrongpre_map', ['test_hard_wrongpre_donor_map.csv.gz'],
     'c3b446b209ae42535ccdf1df35be4e4dd257cd2e0be4c6da2078e87000c67017',
     'manifests/wrong_pre/test_hard_wrongpre_donor_map.csv.gz'),
    ('phase7dd_metrics_all', ['test_metrics_all_conditions.csv'],
     'cf9ee06bc1c7fa0f166daa6fad1c340e75f835cf680eb92e52beb45bae11cc0c',
     'results/heldout_events/test_metrics_all_conditions.csv'),
    ('phase7dd_metrics_clean', ['test_metrics_clean.csv'],
     'cb8a0bb58acc76375b948ff9c6d44ecc333153f01ba7a503e7da1fc82215bcfc',
     'results/heldout_events/test_metrics_clean.csv'),
    ('phase7dd_per_class_all', ['test_per_class_f1_all_conditions.csv'],
     '34b1930d007cea21c10336dd5f95e391130b3e3f66cfeee24cd0c30d306c27bc',
     'results/heldout_events/test_per_class_f1_all_conditions.csv'),
    ('phase7dd_per_event', ['test_per_event_metrics.csv'],
     '74309091addcfc9ac0858e578e908d0c653cd988b7006f24fdd88af70f09150b',
     'results/heldout_events/test_per_event_metrics.csv'),
    ('phase7dd_event_summary', ['test_event_macro_summary.csv'],
     '3ed8b2a05f9cd882759c5562784547cb7332fdf0d9d1e44c7c48a410a914b006',
     'results/heldout_events/test_event_macro_summary.csv'),
    ('phase7dd_leave_one_event_out', ['test_leave_one_event_out.csv'],
     'a41b9ca215451704a57c2496553148bb86265cb1dedd709d314f9a07b3ff231a',
     'results/heldout_events/test_leave_one_event_out.csv'),
    ('phase7dd_bootstrap_all', ['test_scene_bootstrap_all.csv'],
     '7330b9341fb6707bab08ec633b8ac060dec71d8346441a45ecd880330e3f4504',
     'results/heldout_events/test_scene_bootstrap_all.csv'),
    ('phase7dd_utility', ['test_neural_utility.json'],
     '073f7a945fd898c8bbe318f060fa0ebfbf5e12199662c9d20a9b4d2db2235901',
     'results/heldout_events/test_neural_utility.json'),
    ('phase7dd_protocol_record', ['phase7d_d_protocol_record.json'],
     '1fffb11cbbb09dd7c2790d0fd46fda153a402f06afff2d0907e154300268985c',
     'results/heldout_events/phase7d_d_protocol_record.json'),
    ('phase7dd_results_index', ['results_index.json'],
     'c9b0537a75f60f1d0f4f9a6b93141bece0a6cf3447c88fd603ec6f6fdcd23146',
     'results/heldout_events/results_index.json'),
]


def candidate_loose_files(vault: Path, names: set[str]):
    for p in vault.rglob('*'):
        if p.is_file() and p.name in names and p.suffix.lower() != '.zip':
            yield p


def zip_files(vault: Path):
    return sorted((p for p in vault.rglob('*.zip') if p.is_file()), key=lambda p: str(p).lower())


def find_exact_sources(vault: Path, basenames: list[str], expected_sha: str, zip_cache):
    names = set(basenames)
    hits = []

    # Loose/extracted copies.
    for p in candidate_loose_files(vault, names):
        try:
            if sha256_file(p) == expected_sha:
                hits.append({'kind':'file','source':str(p),'path':p})
        except OSError:
            pass

    # Members inside original ZIP evidence packages.
    for zp, members in zip_cache.items():
        matching = [m for m in members if Path(m).name in names and not m.endswith('/')]
        if not matching:
            continue
        with zipfile.ZipFile(zp) as z:
            for member in matching:
                data = z.read(member)
                if sha256_bytes(data) == expected_sha:
                    hits.append({'kind':'zip','source':f'{zp}::{member}','zip':zp,'member':member})
    return hits


def restore_one(hit, dest: Path):
    dest.parent.mkdir(parents=True, exist_ok=True)
    if hit['kind'] == 'file':
        shutil.copy2(hit['path'], dest)
    else:
        with zipfile.ZipFile(hit['zip']) as z:
            data = z.read(hit['member'])
        dest.write_bytes(data)


def main():
    ap = argparse.ArgumentParser(description='Restore exact DamageACT-U canonical artifacts from loose files or original ZIP packages.')
    ap.add_argument('--evidence-vault', required=True)
    ap.add_argument('--repo-root', default='.', help='DamageACT-U repository root (default: current directory).')
    ap.add_argument('--report', default='audit/restoration_report_v2.json')
    args = ap.parse_args()

    vault = Path(args.evidence_vault).resolve()
    repo = Path(args.repo_root).resolve()
    if not vault.is_dir():
        raise FileNotFoundError(vault)
    if not (repo / 'pyproject.toml').is_file():
        raise RuntimeError(f'--repo-root does not look like the DamageACT-U repository: {repo}')

    # Read only ZIP central directories first. Large segment-state ZIPs are not decompressed unless a basename matches.
    zip_cache = {}
    for zp in zip_files(vault):
        try:
            with zipfile.ZipFile(zp) as z:
                zip_cache[zp] = z.namelist()
        except zipfile.BadZipFile:
            print('WARNING: bad ZIP skipped:', zp)

    report = {
        'vault': str(vault),
        'repo_root': str(repo),
        'artifacts': [],
        'summary': {},
    }
    failures = 0

    for label, basenames, expected, rel_dest in ARTIFACTS:
        dest = repo / rel_dest

        # Never silently overwrite a non-canonical destination.
        if dest.is_file():
            got = sha256_file(dest)
            if got == expected:
                print(f'ALREADY VERIFIED: {label} -> {rel_dest}')
                report['artifacts'].append({
                    'label':label,'status':'already_verified','destination':rel_dest,
                    'expected_sha256':expected,'actual_sha256':got,'sources':[]
                })
                continue
            print(f'ERROR DESTINATION HASH MISMATCH: {label}\n  {dest}\n  expected={expected}\n  actual  ={got}')
            report['artifacts'].append({
                'label':label,'status':'destination_hash_mismatch','destination':rel_dest,
                'expected_sha256':expected,'actual_sha256':got,'sources':[]
            })
            failures += 1
            continue

        hits = find_exact_sources(vault, basenames, expected, zip_cache)
        if not hits:
            print(f'MISSING EXACT ARTIFACT: {label} | basenames={basenames} | sha256={expected}')
            report['artifacts'].append({
                'label':label,'status':'missing','destination':rel_dest,
                'expected_sha256':expected,'sources':[]
            })
            failures += 1
            continue

        # Multiple valid hits are byte-identical by construction; preserve provenance and choose deterministically.
        hits = sorted(hits, key=lambda h: h['source'].lower())
        chosen = hits[0]
        restore_one(chosen, dest)
        got = sha256_file(dest)
        if got != expected:
            raise RuntimeError(f'Post-copy hash mismatch for {label}: {got} != {expected}')
        print(f'RESTORED: {label} -> {rel_dest} | exact_copies_found={len(hits)}')
        report['artifacts'].append({
            'label':label,'status':'restored','destination':rel_dest,
            'expected_sha256':expected,'actual_sha256':got,
            'chosen_source':chosen['source'],'sources':[h['source'] for h in hits]
        })

    counts = {}
    for row in report['artifacts']:
        counts[row['status']] = counts.get(row['status'], 0) + 1
    report['summary'] = counts
    report_path = repo / args.report
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2), encoding='utf-8')

    print('\nRESTORATION SUMMARY:', json.dumps(counts, sort_keys=True))
    print('REPORT:', report_path)
    if failures:
        raise SystemExit(f'RESTORATION INCOMPLETE: {failures} required canonical artifacts were not restored/verified.')
    print('RESTORATION COMPLETE: every listed canonical artifact is hash-verified.')


if __name__ == '__main__':
    main()
